### ISSUE TITLE
SubProperties

### ISSUE THREAD

**Issue by Tobisaninfo** [saxsys/SynchronizeFX#34]
Kann ich in einer ObjectProperty weiter Properties haben, die über das Netzwerk übertragen werden ?

**Comment by rbi** [comment]
Das geht leider im Moment nur indirekt (siehe #31). Man benötigt dazu Momentan einen Wrapper, also z.B. `ObjectProperty<MyWrapper>`. Properties in der `MyWrapper` Klasse werden Synchronisiert und auch das auswechseln der `MyWrapper` Instanz in der `ObjectProperty` wird synchronisiert.

Eine `ObjectProperty<IntegerProperty>` wird leider nicht korrekt synchronisiert aber ich freue mich über jeden Code-Beitrag der das implementiert. ;-)
