### ISSUE TITLE
Close JavaFX Application

### ISSUE THREAD

**Issue by Tobisaninfo** [saxsys/SynchronizeFX#36]
Wenn ich eine JavafX Application schließen möchte, ist das nur über System.exit(0) möglich. Dabei habe ich das Problem auf Client Seite. Beim Server habe ich keine Ahnung. Ich habe auch die disconnect() Methode verwendet. Ist das ein Bug oder geht das nicht ohne die exit(0) Methode?

**Comment by rbi** [comment]
Es sollte ohne System.exit gehen. Das dürfte dieser Bug sein: https://github.com/saxsys/SynchronizeFX/issues/9
