### ISSUE TITLE
Sicherheit

### ISSUE THREAD

**Issue by Tobisaninfo** [saxsys/SynchronizeFX#40]
Hallo,
Habe habe eine Frage zum Thema Sicherheit. Gibt es eine Möglichkeit einer serverseitigen Authentifikation? Oder eine andere Möglichkeit, sodass nicht jeder sich mit dem Server ohne weiteres verbinden kann? Danke für eine Antwort.

**Comment by rbi** [comment]
Es ist möglich aber momentan etwas umständlich. Mit dem plain-TCP-basierten Server, der durch den Builder gebaut wird, ist Authentifizierung momentan nicht möglich (siehe #7). 

Man kann aber einen SynchronizeFX Server basierend auf der JSR-356 WebSocket API aufsetzen. Dafür benötigt man einen Container der diese API unterstützt (z.B. Tomcat 8). Authentifikation und Verschlüsslung kann man dann über die Möglichkeiten des entsprechenden Containers konfigurieren.

Leider ist das Vorgehen momentan nicht dokumentiert. Man muss einen Server manuell zusammenbauen, ähnlich wie es der Builder macht. Das kann man sich [hier](https://github.com/saxsys/SynchronizeFX/tree/e8105869b42c8d848c592acaef5629c859507bce/synchronizefx/src/main/java/de/saxsys/synchronizefx) ansehen. Anstatt des `NettyServer` nutzt man einen `SynchronizeFxServer` aus der Klasse `SychronizeFXWebsocketServer`. Dieser ist im folgenden Maven Artefakt zu finden:

```
<groupId>de.saxsys.synchronizefx</groupId>
<artifactId>websocket-transmitter</artifactId>
```

Auf Clientseite nutzt man eine `NettyWebsocketClient` aus dem Artefakt:

```
<groupId>de.saxsys.synchronizefx</groupId>
<artifactId>netty-transmitter</artifactId>
```

**Comment by Tobisaninfo** [comment]
Danke für deine Antwort, nur leider ist es echt nicht einfach, das ohne wirklicher Dokumentation zu machen. Deswegen lege ich das hier erstmal still. Vielleicht greife ich später nochmal dieses Thema auf.
