### ISSUE TITLE
Different model instances for different users

### ISSUE THREAD

**Issue by Tobisaninfo** [saxsys/SynchronizeFX#41]
Is it possible to have different model instances depending on different users?

**Comment by rbi** [comment]
One [SynchronizeFxServer](https://github.com/saxsys/SynchronizeFX/blob/v0.7.0/synchronizefx-core/src/main/java/de/saxsys/synchronizefx/core/clientserver/SynchronizeFxServer.java) instance can manage only one model instance but you can have multiple `SynchronizeFxServer`s. With the Netty/TCP based transimtter you have to open multiple ports to achieve that.

The [JSR 356 WebSocket Based Transmitter](https://github.com/saxsys/SynchronizeFX/blob/v0.7.0/transmitter/websocket-transmitter/src/main/java/de/saxsys/synchronizefx/websocket/SychronizeFXWebsocketServer.java) has built-in support for multiple channels. To use it you need to implement a WebSocket Endpoint and pass received messages to [SychronizeFXWebsocketServer](https://github.com/saxsys/SynchronizeFX/blob/v0.7.0/transmitter/websocket-transmitter/src/main/java/de/saxsys/synchronizefx/websocket/SychronizeFXWebsocketServer.java). When passing new messages you need to decide which channel a message belongs to. In your case you would have a channel for each user.
